controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - base
      - shoulder
      - elbow
      - wrist_pitch
      - wrist_roll
  
