controller_list:
  - name: fake_manipulator_controller
    joints:
      - base
      - shoulder
      - elbow
      - wrist_pitch
      - wrist_roll
  - name: fake_gripper_group_controller
    joints:
      - gripper_movable